version: 2.1

orbs:
  slack: circleci/slack@4.1
executors:
  node-executor:
    docker:
      - image: circleci/node:latest
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-nodejs:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Generate Coverage Report
          command: npm run test:coverage
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: coverage
          destination: coverage-report
      - slack/notify:
          message: "This is Mike Forehand submitting the slack assignment"
          channel: "#general"
          token: ${SLACK_OAUTH_TOKEN}

  build-dummy-artifacts:
    executor: python-executor
    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

  fetch-artifacts:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Fetch Artifacts
          command: |
            curl -H "Circle-Token: CCIPAT_Rh1PkD26K5pGFkLBtR8ANa_20b3fff2668847179838bf70480f96701a4b729c" \
                 https://circleci.com/api/v1.1/project/github/mgforehand/ut_4200_code_coverage/1.0.207522-d583bc78/artifacts

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-nodejs
      - build-dummy-artifacts
      - fetch-artifacts
